spring:
  datasource:
    url: jdbc:mysql://rm-2ze31smx17n76u0iwpo.mysql.rds.aliyuncs.com:3306/general_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1qaz@WSX

    redis:
        host: 192.168.31.231
        port: 6379

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
